#!/usr/bin/env python3
"""
plants_to_kml.py — OSINT Village BSides KC 2026 Toolkit (Wildcard Industries LLC)
From Domain to Dossier · BSides KC 2026 · OSINT Village

Turn a CSV of facility addresses into a KML file for Google Earth /
Google Maps visualization. Perfect for industrial OSINT deliverables:
take the plant list from a 10-K "Properties" section, geocode, and
hand leadership an interactive map instead of a spreadsheet.

Input CSV must have a header row. Minimum columns:
    name,address

Optional columns:
    segment   — folder grouping in KML (e.g. "Construction", "Mining")
    notes     — free text in the KML description
    lat,lon   — if you already have coordinates, skip geocoding

Usage:
    # Geocode addresses via OSM Nominatim (rate-limited, ~1/sec)
    python3 plants_to_kml.py plants.csv -o caterpillar_plants.kml

    # Skip geocoding (use existing lat,lon columns)
    python3 plants_to_kml.py plants.csv -o out.kml --no-geocode

Dependencies:
    pip install simplekml requests
"""

import argparse
import csv
import sys
import time
from pathlib import Path

try:
    import simplekml
except ImportError:
    print("[!] simplekml required: pip install simplekml", file=sys.stderr)
    sys.exit(1)

try:
    import requests
except ImportError:
    requests = None


NOMINATIM = "https://nominatim.openstreetmap.org/search"
USER_AGENT = "osint-village-bsideskc-2026/1.0 (research contact: github.com/Ginsberg5150)"
RATE_LIMIT_SECONDS = 1.1  # Nominatim requires max 1 req/sec


def geocode(address: str) -> tuple:
    """Geocode via OSM Nominatim. Free but rate-limited to 1 req/sec."""
    if requests is None:
        raise RuntimeError("requests not installed (pip install requests)")
    r = requests.get(
        NOMINATIM,
        params={"q": address, "format": "json", "limit": 1},
        headers={"User-Agent": USER_AGENT},
        timeout=10,
    )
    r.raise_for_status()
    data = r.json()
    if not data:
        return None, None
    return float(data[0]["lat"]), float(data[0]["lon"])


SEGMENT_STYLES = {
    # segment_name: (color_hex_aabbggrr, icon_url)
    "default": ("ff0080ff", "http://maps.google.com/mapfiles/kml/shapes/target.png"),
}


def main():
    parser = argparse.ArgumentParser(
        description="Convert facility CSV → Google Earth KML"
    )
    parser.add_argument("csv_file", help="input CSV with header row")
    parser.add_argument("--output", "-o", default="plants.kml",
                        help="output .kml path")
    parser.add_argument("--no-geocode", action="store_true",
                        help="CSV already has lat,lon columns")
    parser.add_argument("--title", default=None,
                        help="KML document title (default: filename)")
    args = parser.parse_args()

    kml = simplekml.Kml()
    kml.document.name = args.title or Path(args.csv_file).stem
    kml.document.description = (
        "Generated by osint-village-bsideskc-2026 / plants_to_kml.py.\n"
        "Sources: 10-K Properties section, county records, OSM Nominatim geocoding.\n"
        "Admiralty: B2 (source usually reliable, probably true).\n"
        "Open in Google Earth Pro for interactive viewing or export to image."
    )

    folders = {}
    total = 0
    geocoded = 0
    failed = []

    with open(args.csv_file) as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            print("[!] CSV has no header row", file=sys.stderr)
            sys.exit(1)
        if "name" not in reader.fieldnames or "address" not in reader.fieldnames:
            print("[!] CSV must have 'name' and 'address' columns", file=sys.stderr)
            sys.exit(1)

        for i, row in enumerate(reader, 1):
            total += 1
            name = (row.get("name") or f"Site {i}").strip()
            address = (row.get("address") or "").strip()
            segment = (row.get("segment") or "Unclassified").strip()
            notes = (row.get("notes") or "").strip()

            lat, lon = None, None
            if args.no_geocode:
                try:
                    lat = float(row["lat"])
                    lon = float(row["lon"])
                except (KeyError, ValueError):
                    print(f"[!] {name}: missing lat/lon in --no-geocode mode")
                    failed.append(name)
                    continue
            else:
                # QA fix: pre-filter addresses that don't look geocodable.
                # EPA FRS has ~20% rows like "PORTABLE SOURCE", "BLDG LL",
                # or a highway intersection with no street number. These
                # burn Nominatim rate-limit budget and always fail.
                # Require at least one street number at the start of a token.
                import re
                has_street_number = bool(re.search(r'\b\d{1,6}\b', address))
                if not has_street_number:
                    print(f"[!] {name}: address lacks street number, skipping: {address}")
                    failed.append(name)
                    continue

                print(f"[*] geocoding {i}: {name} — {address}")
                try:
                    lat, lon = geocode(address)
                except Exception as e:
                    print(f"[!] {name}: geocode error: {e}")
                    failed.append(name)
                    continue
                if lat is None:
                    print(f"[!] {name}: no geocode result")
                    failed.append(name)
                    continue
                time.sleep(RATE_LIMIT_SECONDS)

            geocoded += 1

            if segment not in folders:
                folders[segment] = kml.newfolder(name=segment)

            point = folders[segment].newpoint(
                name=name,
                coords=[(lon, lat)],
            )
            description_parts = [f"<b>{name}</b>"]
            if address:
                description_parts.append(f"Address: {address}")
            if segment != "Unclassified":
                description_parts.append(f"Segment: {segment}")
            if notes:
                description_parts.append(f"Notes: {notes}")
            description_parts.append(f"Coordinates: {lat:.4f}, {lon:.4f}")
            point.description = "<br/>".join(description_parts)

    kml.save(args.output)
    print(f"\n[+] KML written: {args.output}")
    print(f"[+] {geocoded}/{total} sites geocoded")
    if failed:
        print(f"[!] failed: {len(failed)}")
        for name in failed:
            print(f"    - {name}")

    print("\nNext steps:")
    print("  1. Open in Google Earth Pro (free desktop app)")
    print("  2. Style points per segment for visual clarity")
    print("  3. Export → 'Save Image' for leadership-ready PNG")
    print("  4. Or share the .kml directly — stakeholders can pan/zoom")


if __name__ == "__main__":
    main()
